ERROR - 2024-05-03 07:00:02 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\MySQLi\Connection.php(186): mysqli->real_connect()
#1 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\app\Models\AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\app\Controllers\Account.php(48): App\Models\AccountModel->getUser()
#6 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#8 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#9 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#11 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\public\index.php(56): CodeIgniter\Boot::bootWeb()
#12 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Commands\Server\rewrite.php(49): require_once('...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\app\Models\AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\app\Controllers\Account.php(48): App\Models\AccountModel->getUser()
#5 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\public\index.php(56): CodeIgniter\Boot::bootWeb()
#11 C:\Users\gtk\Documents\Coding\personal\dalaria_chargen_v2\system\Commands\Server\rewrite.php(49): require_once('...')
#12 {main}
CRITICAL - 2024-05-03 07:00:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: POST, Route: account/signin-process]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Models\AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Account.php(48): App\Models\AccountModel->getUser()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb()
11 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\gtk\\Documents\\Coding\\personal\\dalaria_chargen_v2\\public\\index.php')
ERROR - 2024-05-03 14:14:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-03 14:14:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `users`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-03 14:17:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-03 14:17:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `users`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
