CRITICAL - 2024-05-04 14:15:58 --> ErrorException: Access level to App\Models\AccountModel::$db must be protected (as in class CodeIgniter\BaseModel) or weaker
[Method: POST, Route: account/signin-process]
in APPPATH/Models/AccountModel.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-04 14:16:16 --> ErrorException: Access level to App\Models\AccountModel::$db must be protected (as in class CodeIgniter\BaseModel) or weaker
[Method: POST, Route: account/signin-process]
in APPPATH/Models/AccountModel.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-04 14:16:27 --> ErrorException: Access level to App\Models\AccountModel::$db must be protected (as in class CodeIgniter\BaseModel) or weaker
[Method: POST, Route: account/signin-process]
in APPPATH/Models/AccountModel.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-05-04 14:17:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:17:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(29): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 14:17:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:17:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 14:19:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:19:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 14:19:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:19:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 14:19:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:19:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 14:24:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'Dalaria_Chargen_test'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'Dalaria_Chargen...', Object(SensitiveParameterValue), 'dalaria_chargen', 3306, '', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `p...', Array, false)
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(48): App\Models\AccountModel->getUser(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-05-04 14:24:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `password`
FROM `user`
WHERE `username` = :username:', [...], false)
 3 APPPATH/Models/AccountModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 14:26:35 --> ErrorException: Undefined variable $result
[Method: POST, Route: account/signin-process]
in APPPATH/Models/AccountModel.php on line 35.
 1 APPPATH/Models/AccountModel.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $result', '/volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php', 35)
 2 APPPATH/Controllers/Account.php(48): App\Models\AccountModel->getUser([...])
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signInProcess()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 16:47:01 --> ErrorException: date_default_timezone_set(): Timezone ID 'GMT+1' is invalid
[Method: POST, Route: account/signin-process]
in SYSTEMPATH/CodeIgniter.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'GMT+1\' is invalid', '/volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php', 193)
 2 SYSTEMPATH/CodeIgniter.php(193): date_default_timezone_set('GMT+1')
 3 SYSTEMPATH/Boot.php(299): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:02:30 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: POST, Route: account/signup-process]
in SYSTEMPATH/Database/BaseConnection.php on line 913.
 1 SYSTEMPATH/Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH/Model.php(911): CodeIgniter\Model->builder()
 3 APPPATH/Controllers/Account.php(126): CodeIgniter\Model->__call('insert_user', [...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:02:57 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
[Method: POST, Route: account/signup-process]
in SYSTEMPATH/Database/BaseConnection.php on line 913.
 1 SYSTEMPATH/Model.php(705): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH/Model.php(911): CodeIgniter\Model->builder()
 3 APPPATH/Controllers/Account.php(126): CodeIgniter\Model->__call('insert_user', [...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:04:15 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
[Method: POST, Route: account/signup-process]
in APPPATH/Models/AccountModel.php on line 20.
 1 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 15:05:02 --> mysqli_sql_exception: Duplicate entry 'GTK_TEST' for key 'username' in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(126): App\Models\AccountModel->insertUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-04 15:05:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'GTK_TEST' for key 'username'
[Method: POST, Route: account/signup-process]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 2 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:05:02 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'GTK_TEST' for key 'username'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$2ePX3eOy9nFd7BBUrMr3z.PY5a5gYLw4Td5OnMVfQbxfSrYxwdgPq\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$2ePX3eOy9nFd7BBUrMr3z.PY5a5gYLw4Td5OnMVfQbxfSrYxwdgPq\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 4 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:05:02 --> [Caused by] mysqli_sql_exception: Duplicate entry 'GTK_TEST' for key 'username'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$2ePX3eOy9nFd7BBUrMr3z.PY5a5gYLw4Td5OnMVfQbxfSrYxwdgPq\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$2ePX3eOy9nFd7BBUrMr3z.PY5a5gYLw4Td5OnMVfQbxfSrYxwdgPq\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$2ePX3eOy9nFd7BBUrMr3z.PY5a5gYLw4Td5OnMVfQbxfSrYxwdgPq\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 5 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-04 15:05:54 --> mysqli_sql_exception: Duplicate entry 'GTK_TEST' for key 'username' in /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /volume1/web/chronicles_of_dalaria/chargen/dev/app/Controllers/Account.php(126): App\Models\AccountModel->insertUser(Array)
#6 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
#7 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#8 /volume1/web/chronicles_of_dalaria/chargen/dev/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 /volume1/web/chronicles_of_dalaria/chargen/dev/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /volume1/web/chronicles_of_dalaria/chargen/dev/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-04 15:05:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'GTK_TEST' for key 'username'
[Method: POST, Route: account/signup-process]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 2 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:05:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'GTK_TEST' for key 'username'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$w40LI7dXCMhdPMA1VrNkJuFIWTY.Df7hp8PtBdHKKuMzU26Kw0xQ6\')')
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$w40LI7dXCMhdPMA1VrNkJuFIWTY.Df7hp8PtBdHKKuMzU26Kw0xQ6\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 4 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 15:05:54 --> [Caused by] mysqli_sql_exception: Duplicate entry 'GTK_TEST' for key 'username'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$w40LI7dXCMhdPMA1VrNkJuFIWTY.Df7hp8PtBdHKKuMzU26Kw0xQ6\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$w40LI7dXCMhdPMA1VrNkJuFIWTY.Df7hp8PtBdHKKuMzU26Kw0xQ6\')')
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (\'GTK_TEST\', \'geert@yourzine.nl\', \'TEST\', \'GTK\', \'1986-11-09\', \'123645879745\', \'3a3ca9f190ff044fb4e2d50de1cdf4aa\', \'$2y$10$w40LI7dXCMhdPMA1VrNkJuFIWTY.Df7hp8PtBdHKKuMzU26Kw0xQ6\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `firstname`, `lastname`, `birthday`, `discord`, `hash`, `password`) VALUES (:username:, :email:, :firstname:, :lastname:, :birthday:, :discord:, :hash:, :password:)', [...], false)
 5 APPPATH/Models/AccountModel.php(20): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 17:31:32 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
[Method: POST, Route: account/signup-process]
in APPPATH/Models/AccountModel.php on line 23.
 1 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 17:32:12 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Builder::insert_id()
[Method: POST, Route: account/signup-process]
in APPPATH/Models/AccountModel.php on line 23.
 1 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 17:33:14 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
[Method: POST, Route: account/signup-process]
in APPPATH/Models/AccountModel.php on line 31.
 1 APPPATH/Controllers/Account.php(126): App\Models\AccountModel->insertUser([...])
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Account->signUpProcess()
 3 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
 4 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-04 17:38:15 --> ErrorException: Undefined variable $request
[Method: GET, Route: account/signup-done]
in APPPATH/Views/account/signup_done.php on line 7.
 1 APPPATH/Views/account/signup_done.php(7): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', '/volume1/web/chronicles_of_dalaria/chargen/dev/app/Views/account/signup_done.php', 7)
 2 SYSTEMPATH/View/View.php(234): include('/volume1/web/chronicles_of_dalaria/chargen/dev/app/Views/account/signup_done.php')
 3 SYSTEMPATH/View/View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1171): CodeIgniter\View\View->render('account/signup_done', [], true)
 5 APPPATH/Controllers/Page.php(39): view('account/signup_done')
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Page->view('signup-done')
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Page))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
